# Site settings
title: DentistSmile | Dental Jekyll Theme
description: "A responsive Jekyll theme for dental clinics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg
baseurl: /website.org
destination: ./_site/website.org

components:
  navbar: [Home, About, Treatments, Team, Testimonials, Gallery, Location]
  social-media:
    - { name: facebook, url: //facebook.com }
    - { name: twitter, url: //twitter.com }
    - { name: instagram, url: //instagram.com }
    - { name: youtube, url: //youtube.com }
    - { name: skype, url: //skype.com }
    - { name: feed, url: '#' }

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: DentistSmile
    hero_description: A responsive Jekyll theme for dental clinics.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: contact@yoursite.com
    address: Von schroeders 273, <br> Viña del mar - Chile

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google-verification:
