# Site settings
title: FAFORE | Familia, Fortaleza y Reinserción A.C.
description: "FAFORE, es una asociación civil, creada con el propósito de brindar las herramientas necesarias,  para que las niñas, niños y adolescentes, hij@s de mujeres privadas de la libertad, puedan enfrentar las adversidades que se les presentan día a día, obstaculizando su desarrollo, al no contar con uno de los pilares fundamentales en su  vida, su MADRE."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain

components:
  form: # Contact form
    api-token: # getsimpleform.com API token
  navbar: [ Inicio, Nosotros, Testimonios, Galeria, Patrocinadores, Convenios, Localizanos ]
  social-media:
    - { name: facebook, url: "//www.facebook.com/profile.php?id=100087547196288&mibextid=ZbWKwL" }
    - { name: instagram, url: "//instagram.com/fafore_ac?utm_source=qr&igshid=OGU0MmVlOWVjOQ==" }

# Testimonials
testimonials:
  testimonials_img: parallax.jpg

# Footer
copyright: © 2023 FAFORE - Todos los derecho reservados

# Build settings
markdown: kramdown

exclude: [
  package.json,
  Gruntfile.js,
  node_modules,
  .sass-cache,
  Gemfile,
  Gemfile.lock,
  .gitignore
]

# Theme Settings
analytics: 
google-verification:
